# Utility functions for filtering Wikipedia categories

MAINTENANCE_KEYWORDS = [
    "Articles with",
    "All articles with",
    "Articles containing",
    "CS1 maint",
    "Use dmy dates",
    "Wikipedia",
    "Short description",
    "Commons category",
    "Weblink offline",
    "Unverständliche Artikel",
    "Wartungskategorie",
    "Maintenance",
    "Cleanup",
    "Disambiguation",
    "Stub",
    "Orphaned articles",
    "Dead external links",
    "Unsourced statements",
    "Articles needing",
    "Pages with",
    "Articles lacking",
    "Articles to be",
    "Articles that may",
    "Articles using",
    "Articles covered",
    "Articles which",
    "Articles where",
    "Articles without",
    "Articles that have",
    "Articles needing expert attention",
    "Articles with close paraphrasing",
    "Articles with peacock terms",
    "Articles with weasel words",
    "Articles with excessive see also sections",
    "Articles with specifically marked weasel-worded phrases",
    "Articles with unsourced statements",
    "Articles with disputed statements",
    "Articles with dead external links",
    "Articles with permanently dead external links",
    "Articles with broken or outdated citations",
    "Articles with limited geographic scope",
    "Articles with topics of unclear notability",
    "Articles with trivia sections",
    "Articles with obsolete information",
    "Articles with minor POV problems",
    "Articles with excessive dablinks",
    "Articles with close paraphrasing of public domain sources",
    "Articles with empty sections",
    "Articles with bare URLs for citations",
    "Articles with dead links to other websites",
    "Articles with incomplete citations",
    "Articles needing additional references",
    "Articles needing additional categories",
    "Articles needing expert attention by month",
    "Articles needing link rot cleanup",
    "Articles needing more viewpoints",
    "Articles needing sections",
    "Articles needing the year an event occurred",
    "Articles requiring tables",
    "Articles slanted towards recent events",
    "Articles sourced by IMDb",
    "Articles sourced only by IMDb",
    "Articles that may be too long",
    "Articles that may contain original research",
    "Articles that need to differentiate between fact and fiction",
    "Articles to be expanded",
    "Articles to be split",
    "Articles with a promotional tone",
    "Articles with broken or outdated citations",
    "Articles with close paraphrasing",
    "Articles with disputed statements",
    "Articles with excessive see also sections",
    "Articles with ibid",
    "Articles with improper non-free content",
    "Articles with limited geographic scope",
    "Articles with links needing disambiguation",
    "Articles with minor POV problems",
    "Articles with neologism issues",
    "Articles with obsolete information",
    "Articles with peacock terms",
    "Articles with sections that need to be turned into prose",
    "Articles with specifically marked weasel-worded phrases",
    "Articles with topics of unclear notability",
    "Articles with trivia sections",
    "Articles with unsourced statements",
    "Articles with weasel words",
    "Attempted de-orphan",
    "BLP articles lacking sources",
    "Categories for discussion",
    "Copied and pasted articles and sections",
    "Current events",
    "Dead-end pages",
    "Disambiguation pages in need of cleanup",
    "Incomplete disambiguation",
    "Incomplete lists",
    "Merge by month",
    "Wikipedia neutral point of view disputes",
    "Pages with excessive dablinks",
    "Pages with non-English text lacking appropriate markup",
    "Orphaned articles",
    "Recently revised",
    "Self-contradictory articles",
    "Uncategorized pages",
    "Deprecated templates",
    "Uncategorized stubs",
    "Unreferenced BLPs",
    "Unreviewed new articles",
    "Unreviewed new articles created via the Article Wizard",
    "Userspace drafts",
    "Use British English",
    "Use British (Oxford) English",
    "Use Canadian English",
    "Use dmy dates",
    "Use mdy dates",
    "User-created public domain files",
    "Userspace drafts created via the Article Wizard",
    "Vague or ambiguous geographic scope",
    "Vague or ambiguous time",
    "Wikipedia articles containing buzzwords",
    "Wikipedia articles in need of updating",
    "Wikipedia articles needing clarification",
    "Wikipedia articles needing context",
    "Wikipedia articles needing copy edit",
    "Wikipedia articles needing factual verification",
    "Wikipedia articles needing page number citations",
    "Wikipedia articles needing reorganization",
    "Wikipedia articles needing rewrite",
    "Wikipedia articles with style issues",
    "Wikipedia articles needing time reference citations",
    "Wikipedia articles that are too technical",
    "Wikipedia articles with plot summary needing attention",
    "Wikipedia articles with possible conflicts of interest",
    "Wikipedia articles without plot summaries",
    "Wikipedia categories needing cleanup",
    "Wikipedia external links cleanup",
    "Wikipedia introduction cleanup",
    "Wikipedia list cleanup",
    "Wikipedia pages needing cleanup",
    "Wikipedia references cleanup",
    "Wikipedia spam cleanup",
    "Wikipedia templates needing cleanup",
    "Wikipedians having been offered adoption",
    "Wikipedia:Weblink offline",
    "CS1 errors",
    "Webarchive template wayback links",
    "All articles containing potentially dated statements",
    "Pages using cite ODNB with id parameter",
    "Pages using Sister project links with hidden wikidata",
    "CS1: long volume value",
    "Pages using gadget WikiMiniAtlas",
    "Pages using multiple image with auto scaled images",
    "Biography with signature",
    "All Wikipedia articles written in American English",
    "All articles with unsourced statements"
]

def filter_category_counts(category_counts: dict) -> dict:
    """
    Remove entries whose category contains any maintenance keyword.
    """
    return {cat: count for cat, count in category_counts.items()
            if not any(kw in cat for kw in MAINTENANCE_KEYWORDS)}
